name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.9'  # Specify your desired Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic checks
        run: |
          python -c "import pandas; print(pandas.__version__)"
          # Add other basic checks if needed

      - name: Set up Node.js environment
        uses: actions/setup-node@v4  # Updated to v5
        with:
          node-version: '18.x'  # Specify the Node.js version you want to use

      - name: Install Node.js dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping Node.js dependency installation."
          fi

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: pythondatacleaner
          path: |
            ./*.py
            ./requirements.txt
            # Include other files you want to upload
